apiVersion: v1
data:
  akatsukisite.conf: |-
    server {
        listen       80;
        server_name  akatsuki;
        location / {
            root   /usr/share/nginx/akatsuki/html;
            index  index.html;
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: akatsukiconf
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: index-html-barbatos
data:
 index.html: |
   <html>
   <h1>Welcome to Barbatos site</h1>
   </br>
   <h2>This is me playing with nginx conf</h2>
   <img src="https://imgs.search.brave.com/AfLpq5XX4tK6TtxoWLDbd_665qDaxYgPAJKBCxVl5aE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NjFyYkhlLTdCbEwu/anBn" />
   </html
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: index-html-akatsuki
data:
 index.html: |
   <html>
   <h1>Welcome to Demo site Akatsuki</h1>
   </br>
   <h2>This is me playing witjh nginx conf</h2>
   <img src="https://sakura-pink.jp/img-items/1-gundam-2024-6-4-1-4.jpg" />
   </html
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: customnginx
  name: customnginx
spec:
  volumes:
  - name: index-html-barbatos
    configMap:
      name: index-html-barbatos
  - name: index-html-akatsuki
    configMap:
      name: index-html-akatsuki
  - name: akatsukiconf
    configMap:
      name: akatsukiconf
  - name: localvol
    emptyDir: {}
  initContainers:
  - name: copyhtml
    image: busybox
    command:
    - "sh"
    - "-c"
    - "mkdir -p /to/barbatos/; cp /fromcfm1/index.html /to/barbatos/; mkdir -p /to/akatsuki/; cp /fromcfm2/index.html /to/akatsuki/; sleep 15"
    volumeMounts:
    - name: index-html-barbatos
      mountPath: /fromcfm1
    - name: index-html-akatsuki
      mountPath: /fromcfm2
    - name: localvol
      mountPath: /to  
  containers:
  - image: nginx
    name: customnginx
    resources: {}
    volumeMounts:
    - name: localvol
      mountPath: /usr/share/nginx/html
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
