apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: customnginx
  name: customnginx
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: customnginx
status:
  loadBalancer: {}
