K8SSERVER_COUNT = 1
IMAGE = "bento/ubuntu-24.04"

Vagrant.configure("2") do |config|

  (1..K8SSERVER_COUNT).each do |i|
    config.vm.define "cilium#{i}" do |cilium|
      cilium.vm.box = IMAGE
      cilium.vm.hostname = "cilium#{i+1}"
      cilium.vm.network  :private_network, ip: "192.168.56.#{i+70}"
      cilium.vm.provision "shell", privileged: true,  path: "scripts/k8s_install.sh"
      cilium.vm.provision "file", source: "scripts/k8s_postconfig.sh", destination: "/home/vagrant/k8s_postconfig.sh"
    end
  end
end
