apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  volumes:
  - name: hostkubelet
    hostPath:
      path: /var/lib/kubelet
      type: Directory
  - name: seccomp-profiles
    secret:
      secretName: customseccompprofilesecret
  - name: localvol
    emptyDir: {}
  initContainers:
  - name: seccomp
    image: busybox
    volumeMounts:
    - name: hostkubelet
      mountPath: /host
    - name: seccomp-profiles
      mountPath: /seccomp
    - name: localvol
      mountPath: /local
    command:
    - "sh"
    - "-c"
    - "mkdir -p /host/seccomp && cp /seccomp/*.json /host/seccomp/; test -f /host/seccomp/customprofile.json && echo 'customprofile.json exists.' > /local/checkfile"
  containers:
  - name: web
    image: nginx
    securityContext:
      seccompProfile:
        type: Localhost
        localhostProfile: customprofile.json
    volumeMounts:
    - name: localvol
      mountPath: /local
    livenessProbe:
      exec:
        command:
        - cat
        - /local/checkfile
    resources: {}
