apiVersion: v1
data:
  customprofileds.json: ewogICJkZWZhdWx0QWN0aW9uIjogIlNDTVBfQUNUX0xPRyIsCiAgImFyY2hNYXAiOiBbCiAgICB7CiAgICAgICJhcmNoaXRlY3R1cmUiOiAiU0NNUF9BUkNIX1g4Nl82NCIsCiAgICAgICJzdWJBcmNoaXRlY3R1cmVzIjogWwogICAgICAgICJTQ01QX0FSQ0hfWDg2IiwKICAgICAgICAiU0NNUF9BUkNIX1gzMiIKICAgICAgXQogICAgfQogIF0sCiAgInN5c2NhbGxzIjogWwogICAgewogICAgICAibmFtZXMiOiBbCiAgICAgICAgImFjY2VwdCIsCiAgICAgICAgImFjY2VwdDQiLAogICAgICAgICJhY2Nlc3MiLAogICAgICAgICJicmsiLAogICAgICAgICJjbG9zZSIsCiAgICAgICAgImR1cCIsCiAgICAgICAgImR1cDIiLAogICAgICAgICJkdXAzIiwKICAgICAgICAiZXBvbGxfY3JlYXRlMSIsCiAgICAgICAgImVwb2xsX2N0bCIsCiAgICAgICAgImVwb2xsX3B3YWl0IiwKICAgICAgICAiZXZlbnRmZDIiLAogICAgICAgICJleGVjdmUiLAogICAgICAgICJleGl0IiwKICAgICAgICAiZXhpdF9ncm91cCIsCiAgICAgICAgImZzdGF0IiwKICAgICAgICAiZnV0ZXgiLAogICAgICAgICJnZXRwaWQiLAogICAgICAgICJnZXRwcGlkIiwKICAgICAgICAiZ2V0cmFuZG9tIiwKICAgICAgICAibWFkdmlzZSIsCiAgICAgICAgIm1tYXAiLAogICAgICAgICJtcHJvdGVjdCIsCiAgICAgICAgIm11bm1hcCIsCiAgICAgICAgIm5hbm9zbGVlcCIsCiAgICAgICAgIm9wZW5hdCIsCiAgICAgICAgInBpcGUyIiwKICAgICAgICAicHJlYWQ2NCIsCiAgICAgICAgInBybGltaXQ2NCIsCiAgICAgICAgInJlYWQiLAogICAgICAgICJyZWN2ZnJvbSIsCiAgICAgICAgInJlY3Ztc2ciLAogICAgICAgICJydF9zaWdhY3Rpb24iLAogICAgICAgICJydF9zaWdwcm9jbWFzayIsCiAgICAgICAgInJ0X3NpZ3JldHVybiIsCiAgICAgICAgInNlbmRtc2ciLAogICAgICAgICJzZW5kdG8iLAogICAgICAgICJzZXRpdGltZXIiLAogICAgICAgICJzZXRzb2Nrb3B0IiwKICAgICAgICAic2lnYWx0c3RhY2siLAogICAgICAgICJzb2NrZXQiLAogICAgICAgICJzdGF0IiwKICAgICAgICAid3JpdGUiLAogICAgICAgICJ3cml0ZXYiCiAgICAgIF0sCiAgICAgICJhY3Rpb24iOiAiU0NNUF9BQ1RfQUxMT1ciCiAgICB9CiAgXQp9Cg==
kind: Secret
metadata:
  name: anothercustomseccompprofilesecret
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: customseccompprofileset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: seccomp-ds
  template:
    metadata:
      labels:
        name: seccomp-ds
    spec:
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: copycustomseccomp
        image: busybox
        resources: {}
        volumeMounts:
        - name: hostkubelet
          mountPath: /host
        - name: seccomp-profiles
          mountPath: /seccomp
        - name: localvol
          mountPath: /local
        command:
        - "sh"
        - "-c"
        - "mkdir -p /host/seccomp && cp /seccomp/*.json /host/seccomp/; test -f /host/seccomp/customprofileds.json && echo 'customprofileds.json exists.' > /local/checkfile; sleep 15"
      terminationGracePeriodSeconds: 30
      volumes:
      - name: hostkubelet
        hostPath:
          path: /var/lib/kubelet
          type: Directory
      - name: seccomp-profiles
        secret:
          secretName: anothercustomseccompprofilesecret
      - name: localvol
        emptyDir: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-testds
  labels:
    app: ginx-testds
spec:
  volumes:
  - name: hostkubelet
    hostPath:
      path: /var/lib/kubelet
      type: Directory
  containers:
  - name: web
    image: nginx
    securityContext:
      seccompProfile:
        type: Localhost
        localhostProfile: customprofileds.json
    volumeMounts:
    - name: hostkubelet
      mountPath: /host
      readOnly: true
    readinessProbe:
      exec:
        command:
        - "sh"
        - "-c"
        - test -f /host/seccomp/customprofileds.json && echo 'customprofileds.json exists.'
      initialDelaySeconds: 20
      periodSeconds: 5

    resources: {}

