apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sample
  name: sample
spec:
# Seccomp config
  securityContext:
    seccompProfile:
      type: RuntimeDefault
# Seccomp config end      
  containers:
  - image: nginx
    name: sample
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}