apiVersion: v1
kind: Pod
metadata:
  labels:
    run: amicontained-nodeselector
  name: amicontained-nodeselector
spec:
  affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: seccompDefaultEnabled
                operator: In
                values:
                - "true" 
#  securityContext:
#    seccompProfile:
#      type: Unconfined #RuntimeDefault #
  containers:
    - args:
        - amicontained
      image: yumemaru1979/amicontained
      name: amicontained-nodeselector
      securityContext:
        allowPrivilegeEscalation: false
