apiVersion: v1
kind: Namespace
metadata:
  name: certificates
spec: {}
status: {}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-ciliumgateway-to-ref-secrets
  namespace: certificates
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: Gateway
    namespace: ciliumgateway
  to:
  - group: ""
    kind: Secret           
---    
# Create Secret for TLS certs
# k create secret tls k8scilium1tls --key <path_to_key> --cert <path_to_cert> -n certificates --dry-run=client -o yaml

