apiVersion: v1
kind: Namespace
metadata:
  name: ciliumgateway
spec: {}
status: {}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: shared-gw
  namespace: ciliumgateway
spec:
  gatewayClassName: custom-cilium-gateway-class
  listeners:
  - protocol: HTTP
    port: 80
    name: shared-gw
    allowedRoutes:
      namespaces:
        #from: All
        from: Selector
        selector:
          #matchLabels:
          #  kubernetes.io/metadata.name: "gundam"
          matchExpressions:
          - { key: kubernetes.io/metadata.name, operator: In, values: [gundam,demoapp] }
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: shared-gw-tls
  namespace: ciliumgateway
spec:
  gatewayClassName: custom-cilium-gateway-class
  listeners:
  - protocol: HTTPS
    port: 443
    name: cilium-gateway
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchExpressions:
          - { key: kubernetes.io/metadata.name, operator: In, values: [gundam,demoapp] }
    tls:
      certificateRefs:
      - kind: Secret
        group: ""
        name: k8scilium1tls
        namespace: certificates
---
