K8SSERVER_COUNT = 1
K8SNODE_COUNT = 1
IMAGE = "bento/ubuntu-24.04"

Vagrant.configure("2") do |config|

  (1..K8SSERVER_COUNT).each do |i|
    config.vm.define "calicomaster#{i}" do |calicomasters|
      calicomasters.vm.box = IMAGE
      calicomasters.vm.hostname = "calicomaster#{i}"
      calicomasters.vm.network  :private_network, ip: "192.168.56.#{i+21}"
      calicomasters.vm.provision "shell", privileged: true,  path: "scripts/k8s_install.sh"
      calicomasters.vm.provision "file", source: "scripts/k8s_postconfig.sh", destination: "/home/vagrant/k8s_postconfig.sh"
    end
  end

  (1..K8SNODE_COUNT).each do |i|
    config.vm.define "caliconode#{i}" do |caliconodes|
      caliconodes.vm.box = IMAGE
      caliconodes.vm.hostname = "caliconode#{i}"
      caliconodes.vm.network  :private_network, ip: "192.168.56.#{i+22}"
      caliconodes.vm.provision "shell", privileged: true,  path: "scripts/k8s_node_install.sh"
      caliconodes.vm.provision "file", source: "scripts/k8s_postconfig.sh", destination: "/home/vagrant/k8s_node_postconfig.sh"
    end
  end
end
