apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionPolicy
metadata:
  name: test-patch-pod-security-on-ppr-namespaces
spec:
  # Target only pods
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]

  # Condition : Apply only if the namespace has the label `env` equal to `ppr`
#  matchConditions:
#    - name: "has-env-ppr-label"
#      expression: >
#        has(namespaceObject.metadata.labels) &&
#        'env' in namespaceObject.metadata.labels &&
#        namespaceObject.metadata.labels['env'] == 'ppr'

  # Comportement en cas d'échec
  failurePolicy: Fail
  reinvocationPolicy: IfNeeded

  # Mutation : Ajouter les labels de Pod Security Admission
  mutations:
  - patchType: "JSONPatch"
    jsonPatch:
      expression: >
        has(object.spec.securityContext) ?
        [
          JSONPatch{
            op: "add", 
            path: "/spec/securityContext/runAsUser",
            value: 1000
          },
          JSONPatch{
            op: "add", 
            path: "/spec/securityContext/runAsNonRoot",
            value: true
          }
        ]
        :
        [
          JSONPatch{
            op: "add", 
            path: "/spec/securityContext",
            value: {"runAsUser": 1000}
          },
          JSONPatch{
            op: "add", 
            path: "/spec/securityContext",
            value: {"runAsNonRoot": true}
          }
        ]
  - patchType: "JSONPatch"
    jsonPatch:
      expression: >
        has(object.spec.containers[0].securityContext) ?
        [
          JSONPatch{
            op: "add", 
            path: "/spec/containers/0/securityContext/runAsUser",
            value: 1000
          },
          JSONPatch{
            op: "add", 
            path: "/spec/containers/0/securityContext/runAsNonRoot",
            value: true
          },
          JSONPatch{
            op: "add", 
            path: "/spec/containers/0/securityContext/allowPrivilegeEscalation",
            value: false
          }
        ]
        :
        [
          JSONPatch{
            op: "add", 
            path: "/spec/containers/0/securityContext",
            value: {"runAsUser": 1000}
          },
          JSONPatch{
            op: "add", 
            path: "/spec/containers/0/securityContext",
            value: {"runAsNonRoot": true}
          },
          JSONPatch{
            op: "add",
            path: "/spec/containers/0/securityContext/allowPrivilegeEscalation",
            value: false
          }
        ]
  - patchType: "JSONPatch"
    jsonPatch:
      expression: >
        has(object.metadata.annotations) ?
        [
          JSONPatch{
            op: "add",
            path: "/metadata/annotations/" + jsonpatch.escapeKey("policy.modifiedby.com/test-patch-pod-security-on-ppr-namespaces"),
            value: "true"
          }
        ]
        :
        [
          JSONPatch{
            op: "add",
            path: "/metadata/annotations",
            value: {"policy.modifiedby.com/test-patch-pod-security-on-ppr-namespaces": "true"}
          }
        ]
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: test-patch-pod-security-on-ppr-namespaces-binding
spec:
  policyName: test-patch-pod-security-on-ppr-namespaces
  matchResources:
    namespaceSelector:
      matchLabels:
        env: ppr