apiVersion: v1
kind: Pod
metadata:
  labels:
    run: seccomppod
  name: seccomppod
spec:
  securityContext: 
    seccompProfile:
      type: RuntimeDefault
  containers:
  - image: nginx
    name: seccomppod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
