apiVersion: v1
kind: Namespace
metadata:
  name: cksprep2
  labels: 
    env: dev
spec: {}
status: {}
---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: readonly-sa
  namespace: cksprep2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: cksprep2
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: cksprep2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: readonly-sa
  namespace: cksprep2
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: no-token-pod
  name: no-token-pod
  namespace: cksprep2
spec:
  automountServiceAccountToken: false
  containers:
  - image: nginx:1.25
    name: no-token-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
