
apiVersion: v1
kind: ConfigMap
metadata:
  name: psaparameters
  namespace: default
data:
  # 
  allowedPSSVersion: "v1.34, v1.35"
  allowedPSSLevel: "restricted, baseline"
---
# vap-restrict-psa-with-params.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: restrict-psa-with-params
spec:
  failurePolicy: Fail
  paramKind:
    apiVersion: v1
    kind: ConfigMap
  matchConstraints:
    resourceRules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["namespaces"]
    excludeResourceRules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      operations: ["*"]
      resources: ["namespaces"]
      resourceNames: ["kube-system", "kube-public", "kube-node-lease"]
  validations:
  - expression: >
      has(object.metadata.labels) &&
      "pod-security.kubernetes.io/enforce" in object.metadata.labels &&
      object.metadata.labels["pod-security.kubernetes.io/enforce"] in params.data.allowedPSSLevel.split(",")
    messageExpression: >
      'Operation ' + request.operation + ' on Namespace "' + object.metadata.name +
      '" failed: the label "pod-security.kubernetes.io/enforce" must have a value among: ' +
      params.data.allowedPSSLevel + '. Current value: ' +
      (has(object.metadata.labels) && "pod-security.kubernetes.io/enforce" in object.metadata.labels ?
       object.metadata.labels["pod-security.kubernetes.io/enforce"] : 'undefined')
    reason: Invalid  
#---    
#apiVersion: admissionregistration.k8s.io/v1
#kind: ValidatingAdmissionPolicy
#metadata:
#  name: restrict-psa-enforce-version-with-params
#spec:
#  failurePolicy: Fail
#  paramKind:
#    apiVersion: v1
#    kind: ConfigMap
#  matchConstraints:
#    resourceRules:
#    - apiGroups: [""]
#      apiVersions: ["v1"]
#      operations: ["CREATE", "UPDATE"]
#      resources: ["namespaces"]
#  validations:
#  - expression: >
#      has(object.metadata.labels) &&
#      "pod-security.kubernetes.io/enforce-version" in object.metadata.labels &&
#      object.metadata.labels["pod-security.kubernetes.io/enforce-version"] in params.data.allowedPSSVersion.split(",")
#    messageExpression: >
#      'Operation ' + request.operation + ' on Namespace "' + object.metadata.name +
#      '" failed: the label "pod-security.kubernetes.io/enforce-version" must have a value among: ' +
#      params.data.allowedPSSVersion + '. Current value: ' +
#      (has(object.metadata.labels) && "pod-security.kubernetes.io/enforce-version" in object.metadata.labels ?
#       object.metadata.labels["pod-security.kubernetes.io/enforce-version"] : 'undefined')
#    reason: Invalid 
#---    
#apiVersion: admissionregistration.k8s.io/v1
#kind: ValidatingAdmissionPolicy
#metadata:
#  name: restrict-psa-audit-version-with-params
#spec:
#  failurePolicy: Fail
#  paramKind:
#    apiVersion: v1
#    kind: ConfigMap
#  matchConstraints:
#    resourceRules:
#    - apiGroups: [""]
#      apiVersions: ["v1"]
#      operations: ["CREATE", "UPDATE"]
#      resources: ["namespaces"]
#  validations:
#  - expression: >
#      has(object.metadata.labels) &&
#      "pod-security.kubernetes.io/audit-version" in object.metadata.labels &&
#      object.metadata.labels["pod-security.kubernetes.io/audit-version"] in params.data.allowedPSSVersion.split(",")
#    messageExpression: >
#      'Operation ' + request.operation + ' on Namespace "' + object.metadata.name +
#      '" failed: the label "pod-security.kubernetes.io/audit-version" must have a value among: ' +
#      params.data.allowedPSSVersion + '. Current value: ' +
#      (has(object.metadata.labels) && "pod-security.kubernetes.io/audit-version" in object.metadata.labels ?
#       object.metadata.labels["pod-security.kubernetes.io/audit-version"] : 'undefined')
#    reason: Invalid     
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: restrict-pss-version-with-params-binding
spec:
  policyName: restrict-psa-with-params
  validationActions: ["Audit","Deny"]
  paramRef:
    name: psaparameters      
    namespace: default            
    parameterNotFoundAction: Deny 
  