apiVersion: v1
kind: Namespace
metadata:
  name: cksprep4
  labels:
    env: dev
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: seccomp-pod
  name: seccomp-pod
  namespace: cksprep4
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - image: nginx:1.25
    name: seccomp-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
