apiVersion: v1
kind: Namespace
metadata:
  name: cksprep5
  labels:
    env: prd
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: conforme
  name: conforme
  namespace: cksprep5
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
  - image: nginx:1.25
    name: conforme
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: non-conforme
  name: non-conforme
  namespace: cksprep5
spec:
  containers:
  - image: nginx:1.25
    name: non-conforme
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
